require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class BalanceControlApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'BalanceControl')
    end

    # Start a balance transfer
    #
    # Deprecated since Adyen Balance Control API v1
    # @deprecated
    def balance_transfer(request, headers: {})
      Adyen::Deprecation.warn(:balance_transfer, since: 'Adyen Balance Control API v1')
      endpoint = build_endpoint('/balanceTransfer')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
