require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class AndroidFilesCompanyLevelApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Management')
    end

    # Get Android app
    def get_android_app(company_id, id, headers: {})
      endpoint = '/companies/{companyId}/androidApps/{id}'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, company_id, id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get a list of Android apps
    def list_android_apps(company_id, headers: {}, query_params: {})
      endpoint = '/companies/{companyId}/androidApps'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, company_id)
      endpoint += create_query_string(query_params)
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get a list of Android certificates
    def list_android_certificates(company_id, headers: {}, query_params: {})
      endpoint = '/companies/{companyId}/androidCertificates'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, company_id)
      endpoint += create_query_string(query_params)
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Reprocess Android App
    def reprocess_android_app(company_id, id, headers: {})
      endpoint = '/companies/{companyId}/androidApps/{id}'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, company_id, id)
      
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Upload Android App
    def upload_android_app(company_id, headers: {})
      endpoint = '/companies/{companyId}/androidApps'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, company_id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Upload Android Certificate
    def upload_android_certificate(company_id, headers: {})
      endpoint = '/companies/{companyId}/androidCertificates'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, company_id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

  end
end
