require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class MyAPICredentialApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Management')
    end

    # Add allowed origin
    def add_allowed_origin(request, headers: {})
      endpoint = build_endpoint('/me/allowedOrigins')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Generate a client key
    def generate_client_key(headers: {})
      endpoint = build_endpoint('/me/generateClientKey')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get allowed origin details
    def get_allowed_origin_details(origin_id, headers: {})
      endpoint = build_endpoint('/me/allowedOrigins/{originId}', origin_id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get allowed origins
    def get_allowed_origins(headers: {})
      endpoint = build_endpoint('/me/allowedOrigins')
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get API credential details
    def get_api_credential_details(headers: {})
      endpoint = build_endpoint('/me')
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Remove allowed origin
    def remove_allowed_origin(origin_id, headers: {})
      endpoint = build_endpoint('/me/allowedOrigins/{originId}', origin_id)
      
      action = { method: 'delete', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

  end
end
