require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class TerminalThemesMerchantLevelApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Management')
    end

    # Add an asset to a terminal theme
    def add_terminal_theme_asset_for_merchant(merchant_id, id, headers: {}, query_params: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}/assets', merchant_id, id)
      endpoint += create_query_string(query_params)
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Apply a terminal theme
    def apply_terminal_theme_for_merchant(merchant_id, id, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}/apply', merchant_id, id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Create a terminal theme
    def create_terminal_theme_for_merchant(request, merchant_id, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes', merchant_id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Delete an asset from a terminal theme
    def delete_terminal_theme_asset_for_merchant(merchant_id, id, headers: {}, query_params: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}/assets', merchant_id, id)
      endpoint += create_query_string(query_params)
      action = { method: 'delete', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Delete a terminal theme
    def delete_terminal_theme_for_merchant(merchant_id, id, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}', merchant_id, id)
      
      action = { method: 'delete', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Replace a theme asset
    def edit_terminal_theme_asset_for_merchant(merchant_id, id, headers: {}, query_params: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}/assets/replace', merchant_id, id)
      endpoint += create_query_string(query_params)
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get a terminal theme
    def get_terminal_theme_by_id_for_merchant(merchant_id, id, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}', merchant_id, id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # List terminal themes
    def list_terminal_themes_for_merchant(merchant_id, headers: {}, query_params: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes', merchant_id)
      endpoint += create_query_string(query_params)
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Unapply a terminal theme
    def unapply_terminal_theme_for_merchant(merchant_id, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/unapply', merchant_id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Update the metadata of a terminal theme
    def update_terminal_theme_for_merchant(request, merchant_id, id, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/terminalThemes/{id}', merchant_id, id)
      
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
