require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class TerminalSettingsStoreLevelApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Management')
    end

    # Get the terminal logo
    def get_terminal_logo(merchant_id, reference, headers: {}, query_params: {})
      endpoint = build_endpoint('/merchants/{merchantId}/stores/{reference}/terminalLogos', merchant_id, reference)
      endpoint += create_query_string(query_params)
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get the terminal logo
    def get_terminal_logo_by_store_id(store_id, headers: {}, query_params: {})
      endpoint = build_endpoint('/stores/{storeId}/terminalLogos', store_id)
      endpoint += create_query_string(query_params)
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get terminal settings
    def get_terminal_settings(merchant_id, reference, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/stores/{reference}/terminalSettings', merchant_id, reference)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get terminal settings
    def get_terminal_settings_by_store_id(store_id, headers: {})
      endpoint = build_endpoint('/stores/{storeId}/terminalSettings', store_id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Update the terminal logo
    def update_terminal_logo(request, merchant_id, reference, headers: {}, query_params: {})
      endpoint = build_endpoint('/merchants/{merchantId}/stores/{reference}/terminalLogos', merchant_id, reference)
      endpoint += create_query_string(query_params)
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Update the terminal logo
    def update_terminal_logo_by_store_id(request, store_id, headers: {}, query_params: {})
      endpoint = build_endpoint('/stores/{storeId}/terminalLogos', store_id)
      endpoint += create_query_string(query_params)
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Update terminal settings
    def update_terminal_settings(request, merchant_id, reference, headers: {})
      endpoint = build_endpoint('/merchants/{merchantId}/stores/{reference}/terminalSettings', merchant_id, reference)
      
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Update terminal settings
    def update_terminal_settings_by_store_id(request, store_id, headers: {})
      endpoint = build_endpoint('/stores/{storeId}/terminalSettings', store_id)
      
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
