require_relative 'balanceControlService/balance_control_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class BalanceControlService
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'BalanceControlService'
      @client = client
      @version = version
    end

    def balance_control_api
      @balance_control_api ||= Adyen::BalanceControlApi.new(@client, @version)
    end

  end
end
