require_relative 'binLookup/bin_lookup_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class BinLookup
    attr_accessor :service, :version

    DEFAULT_VERSION = 54
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'BinLookup'
      @client = client
      @version = version
    end

    def bin_lookup_api
      @bin_lookup_api ||= Adyen::BinLookupApi.new(@client, @version)
    end

  end
end
