require_relative 'capital/grant_accounts_api'
require_relative 'capital/grant_offers_api'
require_relative 'capital/grants_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class Capital
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'Capital'
      @client = client
      @version = version
    end

    def grant_accounts_api
      @grant_accounts_api ||= Adyen::GrantAccountsApi.new(@client, @version)
    end

    def grant_offers_api
      @grant_offers_api ||= Adyen::GrantOffersApi.new(@client, @version)
    end

    def grants_api
      @grants_api ||= Adyen::GrantsApi.new(@client, @version)
    end

  end
end
