require_relative 'dataProtection/data_protection_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class DataProtection
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'DataProtection'
      @client = client
      @version = version
    end

    def data_protection_api
      @data_protection_api ||= Adyen::DataProtectionApi.new(@client, @version)
    end

  end
end
