require_relative 'disputes/disputes_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class Disputes
    attr_accessor :service, :version

    DEFAULT_VERSION = 30
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'Disputes'
      @client = client
      @version = version
    end

    def disputes_api
      @disputes_api ||= Adyen::DisputesApi.new(@client, @version)
    end

  end
end
