require_relative 'documentCollector/documents_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class DocumentCollector
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'DocumentCollector'
      @client = client
      @version = version
    end

    def documents_api
      @documents_api ||= Adyen::DocumentsApi.new(@client, @version)
    end

  end
end
