require_relative 'foreignExchange/rates_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class ForeignExchange
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'ForeignExchange'
      @client = client
      @version = version
    end

    def rates_api
      @rates_api ||= Adyen::RatesApi.new(@client, @version)
    end

  end
end
