require_relative 'openBanking/account_verification_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class OpenBanking
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'OpenBanking'
      @client = client
      @version = version
    end

    def account_verification_api
      @account_verification_api ||= Adyen::AccountVerificationApi.new(@client, @version)
    end

  end
end
