require_relative 'payment/modifications_api'
require_relative 'payment/payments_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class Payment
    attr_accessor :service, :version

    DEFAULT_VERSION = 68
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'Payment'
      @client = client
      @version = version
    end

    def modifications_api
      @modifications_api ||= Adyen::ModificationsApi.new(@client, @version)
    end

    def payments_api
      @payments_api ||= Adyen::ClassicPaymentsApi.new(@client, @version)
    end

  end
end
