require_relative 'paymentsApp/payments_app_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class PaymentsApp
    attr_accessor :service, :version

    DEFAULT_VERSION = 1
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'PaymentsApp'
      @client = client
      @version = version
    end

    def payments_app_api
      @payments_app_api ||= Adyen::PaymentsAppApi.new(@client, @version)
    end

  end
end
