require_relative 'posMobile/pos_mobile_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class PosMobile
    attr_accessor :service, :version

    DEFAULT_VERSION = 68
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'PosMobile'
      @client = client
      @version = version
    end

    def pos_mobile_api
      @pos_mobile_api ||= Adyen::PosMobileApi.new(@client, @version)
    end

  end
end
