require_relative 'recurring/recurring_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class Recurring
    attr_accessor :service, :version

    DEFAULT_VERSION = 68
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'Recurring'
      @client = client
      @version = version
    end

    def recurring_api
      @recurring_api ||= Adyen::LegacyRecurringApi.new(@client, @version)
    end

  end
end
