require_relative 'storedValue/stored_value_api'

module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class StoredValue
    attr_accessor :service, :version

    DEFAULT_VERSION = 46
    def initialize(client, version = DEFAULT_VERSION)
      @service = 'StoredValue'
      @client = client
      @version = version
    end

    def stored_value_api
      @stored_value_api ||= Adyen::StoredValueApi.new(@client, @version)
    end

  end
end
