require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class BalancesApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'BalancePlatform')
    end

    # Get webhook settings
    def balance_platforms_balance_platform_id_webhooks_webhook_id_settings_get(balance_platform_id, webhook_id, headers: {})
      endpoint = '/balancePlatforms/{balancePlatformId}/webhooks/{webhookId}/settings'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, balance_platform_id, webhook_id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Create a balance webhook setting
    def balance_platforms_balance_platform_id_webhooks_webhook_id_settings_post(request, balance_platform_id, webhook_id, balance_webhook_settings_request, headers: {})
      endpoint = '/balancePlatforms/{balancePlatformId}/webhooks/{webhookId}/settings'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, balance_platform_id, webhook_id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Delete a webhook setting
    def balance_platforms_balance_platform_id_webhooks_webhook_id_settings_setting_id_delete(balance_platform_id, webhook_id, setting_id, headers: {})
      endpoint = '/balancePlatforms/{balancePlatformId}/webhooks/{webhookId}/settings/{settingId}'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, balance_platform_id, webhook_id, setting_id)
      
      action = { method: 'delete', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get a webhook setting
    def balance_platforms_balance_platform_id_webhooks_webhook_id_settings_setting_id_get(balance_platform_id, webhook_id, setting_id, headers: {})
      endpoint = '/balancePlatforms/{balancePlatformId}/webhooks/{webhookId}/settings/{settingId}'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, balance_platform_id, webhook_id, setting_id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Update a webhook setting
    def balance_platforms_balance_platform_id_webhooks_webhook_id_settings_setting_id_patch(request, balance_platform_id, webhook_id, setting_id, patchable_balance_webhook_settings_request, headers: {})
      endpoint = '/balancePlatforms/{balancePlatformId}/webhooks/{webhookId}/settings/{settingId}'.gsub(/{.+?}/, '%s')
      endpoint = endpoint.gsub(%r{^/}, '')
      endpoint = format(endpoint, balance_platform_id, webhook_id, setting_id)
      
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
