require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class PCIQuestionnairesApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'LegalEntityManagement')
    end

    # Calculate PCI status of a legal entity
    def calculate_pci_status_of_legal_entity(request, id, headers: {})
      endpoint = build_endpoint('/legalEntities/{id}/pciQuestionnaires/signingRequired', id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Generate PCI questionnaire
    def generate_pci_questionnaire(request, id, headers: {})
      endpoint = build_endpoint('/legalEntities/{id}/pciQuestionnaires/generatePciTemplates', id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Get PCI questionnaire
    def get_pci_questionnaire(id, pciid, headers: {})
      endpoint = build_endpoint('/legalEntities/{id}/pciQuestionnaires/{pciid}', id, pciid)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get PCI questionnaire details
    def get_pci_questionnaire_details(id, headers: {})
      endpoint = build_endpoint('/legalEntities/{id}/pciQuestionnaires', id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Sign PCI questionnaire
    def sign_pci_questionnaire(request, id, headers: {})
      endpoint = build_endpoint('/legalEntities/{id}/pciQuestionnaires/signPciTemplates', id)
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
