require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class TransferInstrumentsApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'LegalEntityManagement')
    end

    # Create a transfer instrument
    def create_transfer_instrument(request, headers: {})
      endpoint = build_endpoint('/transferInstruments')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Delete a transfer instrument
    def delete_transfer_instrument(id, headers: {})
      endpoint = build_endpoint('/transferInstruments/{id}', id)
      
      action = { method: 'delete', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Get a transfer instrument
    def get_transfer_instrument(id, headers: {})
      endpoint = build_endpoint('/transferInstruments/{id}', id)
      
      action = { method: 'get', url: endpoint }
      @client.call_adyen_api(@service, action, {}, headers, @version)
    end

    # Update a transfer instrument
    def update_transfer_instrument(request, id, headers: {})
      endpoint = build_endpoint('/transferInstruments/{id}', id)
      
      action = { method: 'patch', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
