require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class ClassicModificationsApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Payment')
    end

    # Change the authorised amount
    def adjust_authorisation(request, headers: {})
      endpoint = build_endpoint('/adjustAuthorisation')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Cancel an authorisation
    def cancel(request, headers: {})
      endpoint = build_endpoint('/cancel')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Cancel or refund a payment
    def cancel_or_refund(request, headers: {})
      endpoint = build_endpoint('/cancelOrRefund')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Capture an authorisation
    def capture(request, headers: {})
      endpoint = build_endpoint('/capture')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Create a donation
    #
    # Deprecated 
    def donate(request, headers: {})
      endpoint = build_endpoint('/donate')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Refund a captured payment
    def refund(request, headers: {})
      endpoint = build_endpoint('/refund')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Cancel an authorisation using your reference
    def technical_cancel(request, headers: {})
      endpoint = build_endpoint('/technicalCancel')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Cancel an in-person refund
    def void_pending_refund(request, headers: {})
      endpoint = build_endpoint('/voidPendingRefund')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
