require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class ClassicPaymentsApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Payment')
    end

    # Create an authorisation
    def authorise(request, headers: {})
      endpoint = build_endpoint('/authorise')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Complete a 3DS authorisation
    def authorise3d(request, headers: {})
      endpoint = build_endpoint('/authorise3d')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Complete a 3DS2 authorisation
    def authorise3ds2(request, headers: {})
      endpoint = build_endpoint('/authorise3ds2')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Get the 3DS authentication result
    def get_authentication_result(request, headers: {})
      endpoint = build_endpoint('/getAuthenticationResult')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Get the 3DS2 authentication result
    def retrieve3ds2_result(request, headers: {})
      endpoint = build_endpoint('/retrieve3ds2Result')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
