require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class BinLookupApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'BinLookup')
    end

    # Check if 3D Secure is available
    def get3ds_availability(request, headers: {})
      endpoint = build_endpoint('/get3dsAvailability')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Get a fees cost estimate
    def get_cost_estimate(request, headers: {})
      endpoint = build_endpoint('/getCostEstimate')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
