require_relative '../service'
module Adyen

  # NOTE: This class is auto generated by OpenAPI Generator
  # Ref: https://openapi-generator.tech
  #
  # Do not edit the class manually.
  class LegacyRecurringApi < Service
    attr_accessor :service, :version

    def initialize(client, version = DEFAULT_VERSION)
      super(client, version, 'Recurring')
    end

    # Create new permits linked to a recurring contract.
    #
    # Deprecated since Adyen Recurring API v68
    # @deprecated
    def create_permit(request, headers: {})
      Adyen::Deprecation.warn(:create_permit, since: 'Adyen Recurring API v68')
      endpoint = build_endpoint('/createPermit')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Disable stored payment details
    def disable(request, headers: {})
      endpoint = build_endpoint('/disable')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Disable an existing permit.
    #
    # Deprecated since Adyen Recurring API v68
    # @deprecated
    def disable_permit(request, headers: {})
      Adyen::Deprecation.warn(:disable_permit, since: 'Adyen Recurring API v68')
      endpoint = build_endpoint('/disablePermit')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Get stored payment details
    def list_recurring_details(request, headers: {})
      endpoint = build_endpoint('/listRecurringDetails')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Ask issuer to notify the shopper
    def notify_shopper(request, headers: {})
      endpoint = build_endpoint('/notifyShopper')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

    # Schedule running the Account Updater
    def schedule_account_updater(request, headers: {})
      endpoint = build_endpoint('/scheduleAccountUpdater')
      
      action = { method: 'post', url: endpoint }
      @client.call_adyen_api(@service, action, request, headers, @version)
    end

  end
end
