name: Release request

on:
    workflow_dispatch:
    push:
      branches:
        - develop

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: https://github.com/Adyen/adyen-dotnet-api-library/blob/develop/.github/workflows/release.yml
    secrets: inherit
