name: ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:    
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '4.0'
        ruby: [3.3, 3.4, '4.0', head]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: ruby/setup-ruby@8a836efbcebe5de0fe86b48a775b7a31b5c70c93 # v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rspec
